name: Terraform with OIDC Auth

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # 🔑 Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan \
          -var "client_id=${ARM_CLIENT_ID}" \
          -var "tenant_id=${ARM_TENANT_ID}" \
          -var "subscription_id=${ARM_SUBSCRIPTION_ID}"

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var "client_id=${ARM_CLIENT_ID}" \
          -var "tenant_id=${ARM_TENANT_ID}" \
          -var "subscription_id=${ARM_SUBSCRIPTION_ID}"
